# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: sdk uninstall gradle 6.8.3 && sdk install gradle 5.6.4 # runs during prebuild
